from __future__ import annotations

FIGURE_GUIDE = [
    {
        "figure": 1,
        "pdf_page": 2,
        "article_page": "62",
        "asset": "assets/figures/fig01.jpg",
        "title": "Schéma d'un dispositif d'extraction par foil oscillant",
        "caption": "Fig. 1 — Schéma d'un dispositif typique d'extraction d'énergie par foil oscillant.",
        "focus": "Repérer le pilonnement h(t), le tangage θ(t), l'écoulement U∞ et le damper. Le damper illustre l'accumulation/stockage mais n'est pas modélisé dans l'étude.",
    },
    {
        "figure": 2,
        "pdf_page": 3,
        "article_page": "63",
        "asset": "assets/figures/fig02.jpg",
        "title": "Profils de pilonnement et de tangage",
        "caption": "Fig. 2 — h(t) et θ(t) sur un cycle pour différentes valeurs de β.",
        "focus": "Comparer β=1, 1,5 et 4 : le pilonnement reste sinusoïdal, tandis que le tangage développe des plateaux de plus en plus longs à ±θ₀.",
    },
    {
        "figure": 3,
        "pdf_page": 3,
        "article_page": "63",
        "asset": "assets/figures/fig03.jpg",
        "title": "Angle d'attaque effectif",
        "caption": "Fig. 3 — αeff(t) sur un cycle pour différentes valeurs de β.",
        "focus": "Observer que modifier la forme de θ(t) modifie aussi fortement αeff(t), malgré un angle nominal α₀ fixé.",
    },
    {
        "figure": 4,
        "pdf_page": 4,
        "article_page": "64",
        "asset": "assets/figures/fig04.jpg",
        "title": "Validation du calcul",
        "caption": "Fig. 4 — Comparaison de l'efficacité calculée avec Jones & Platzer.",
        "focus": "Vérifier la cohérence du code entre régime de consommation et régime d'extraction ; les solutions laminaires sont plus faibles que les solutions Euler/panel à cause des effets visqueux.",
    },
    {
        "figure": 5,
        "pdf_page": 4,
        "article_page": "64",
        "asset": "assets/figures/fig05.jpg",
        "title": "Coefficient de puissance moyen en fonction de St",
        "caption": "Fig. 5 — C̄op en fonction de St pour plusieurs β, h₀/c et α₀.",
        "focus": "Chercher le St critique de chaque courbe : C̄op augmente d'abord, atteint un maximum puis décroît. Comparer surtout β=1,25–1,5 au cas β=1 et au cas β=4.",
    },
    {
        "figure": 6,
        "pdf_page": 5,
        "article_page": "65",
        "asset": "assets/figures/fig06.jpg",
        "title": "Rendement total en fonction de St",
        "caption": "Fig. 6 — ηT en fonction de St pour plusieurs β, h₀/c et α₀.",
        "focus": "Le rendement suit une tendance proche de la puissance : optimum intermédiaire de β et forte dégradation de β=4 hors très faible St.",
    },
    {
        "figure": 7,
        "pdf_page": 6,
        "article_page": "66",
        "asset": "assets/figures/fig07.jpg",
        "title": "Maxima de puissance et de rendement versus β",
        "caption": "Fig. 7 — Maxima de C̄op et ηT en fonction de β.",
        "focus": "Cette figure résume l'optimum : les maxima se situent généralement autour de β=1,25 ou 1,5, puis chutent fortement à β=4.",
    },
    {
        "figure": 8,
        "pdf_page": 7,
        "article_page": "67",
        "asset": "assets/figures/fig08.jpg",
        "title": "Décomposition instantanée C_op = Cp1 + Cp2",
        "caption": "Fig. 8 — C_op instantané et contributions Cp1, Cp2 pour β=1, 1,5, 2 et 4.",
        "focus": "Comparer la hausse de Cp1 avec la pénalité de Cp2. À β=1,5 le gain positif domine encore ; à β=4 les pics négatifs liés au moment deviennent majeurs.",
    },
    {
        "figure": 9,
        "pdf_page": 8,
        "article_page": "68",
        "asset": "assets/figures/fig09.jpg",
        "title": "Forces, vitesses et intervalles A-E",
        "caption": "Fig. 9 — C_L, dh/dt, C_M et dθ/dt sur un cycle pour β=1, 1,5 et 4.",
        "focus": "Regarder les signes. A, C et E donnent Cp1 positif ; B et D sont défavorables. À grand β, dθ/dt devient très impulsif, ce qui amplifie la pénalité Cp2.",
    },
    {
        "figure": 10,
        "pdf_page": 9,
        "article_page": "69",
        "asset": "assets/figures/fig10.jpg",
        "title": "Vorticité pour β=1",
        "caption": "Fig. 10 — Contours instantanés de vorticité pour β=1, St=0,35 et α₀=10°.",
        "focus": "Suivre le LEV de t=0 à t=T/2 : formation au bord d'attaque, croissance, déplacement puis convection vers le sillage.",
    },
    {
        "figure": 11,
        "pdf_page": 10,
        "article_page": "70",
        "asset": "assets/figures/fig11.jpg",
        "title": "Vorticité pour β=1,5",
        "caption": "Fig. 11 — Contours instantanés de vorticité pour β=1,5.",
        "focus": "Comparer au cas β=1 : la cinématique modifiée change l'intensité et la position des structures tourbillonnaires pendant le demi-cycle.",
    },
    {
        "figure": 12,
        "pdf_page": 11,
        "article_page": "71",
        "asset": "assets/figures/fig12.jpg",
        "title": "Vorticité pour β=4",
        "caption": "Fig. 12 — Contours instantanés de vorticité pour β=4.",
        "focus": "Le LEV devient plus intense lorsque β augmente, mais le papier souligne que cela ne suffit pas à améliorer la puissance : le coût de moment devient dominant.",
    },
    {
        "figure": 13,
        "pdf_page": 12,
        "article_page": "72",
        "asset": "assets/figures/fig13.jpg",
        "title": "Pression de paroi pour β=1",
        "caption": "Fig. 13 — Distribution instantanée de pression de paroi pour β=1.",
        "focus": "Relier les différences entre pression supérieure et inférieure à C_L et C_M, puis au signe des deux contributions de puissance.",
    },
    {
        "figure": 14,
        "pdf_page": 13,
        "article_page": "73",
        "asset": "assets/figures/fig14.jpg",
        "title": "Pression de paroi pour β=1,5",
        "caption": "Fig. 14 — Distribution instantanée de pression de paroi pour β=1,5.",
        "focus": "Comparer les minima de pression et leur déplacement au cas β=1. La pression traduit l'évolution du LEV et détermine directement les charges hydrodynamiques.",
    },
    {
        "figure": 15,
        "pdf_page": 14,
        "article_page": "74",
        "asset": "assets/figures/fig15.jpg",
        "title": "Pression de paroi pour β=4",
        "caption": "Fig. 15 — Distribution instantanée de pression de paroi pour β=4.",
        "focus": "Autour des inversions rapides, observer les fortes variations de pression qui contribuent au moment opposé au mouvement de tangage et à la pénalité Cp2.",
    },
]


def figures_for_page(pdf_page: int) -> list[dict]:
    return [item for item in FIGURE_GUIDE if item["pdf_page"] == pdf_page]
